# Generated by Django 5.1.7 on 2025-04-23 21:33

import airport_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport_api", "0002_alter_airplane_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="crewmember",
            name="photo",
            field=models.ImageField(
                null=True, upload_to=airport_api.models.crew_member_image_path
            ),
        ),
    ]
