# Generated by Django 5.1.7 on 2025-05-16 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airport_api", "0004_alter_ticket_options_ticket_unique_flight_seat"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"ordering": ("country", "name"), "verbose_name_plural": "cities"},
        ),
        migrations.AlterModelOptions(
            name="route",
            options={"ordering": ("source__city__name", "destination__city__name")},
        ),
        migrations.RemoveIndex(
            model_name="airport",
            name="airport_api_name_e62cd4_idx",
        ),
        migrations.RemoveIndex(
            model_name="city",
            name="airport_api_name_36122a_idx",
        ),
    ]
